### ISSUE TITLE
Review Issue

### ISSUE THREAD

**Issue by Joemungandar** [Joemungandar/MyFirstHaskellProject#1]
@mgudemann Bitte um Feedback, ob das Projekt für Sie sichtbar ist und ich nicht zu viel im Repo drinnen ist.

Außerdem würde es mich noch interessieren, ob es in Haskell als "unschön" gilt, wenn man (so wie in meiner Lib.hs Datei) ein "if"-Statement 5-fach verkettet und falls ja, was es für Alternativen gibt.

**Comment by mgudemann** [comment]
Es wäre besser, wenn Sie nur alles unter `FirstHaskellProjekt` unter Versionskontrolle halten, das äußere Verzeichnis ist nicht notwendig. Außerdem haben Sie so z.B. 2 `.gitignore` Dateien.

**Comment by mgudemann** [comment]
> Außerdem würde es mich noch interessieren, ob es in Haskell als "unschön" gilt, wenn man (so wie in meiner Lib.hs Datei) ein "if"-Statement 5-fach verkettet und falls ja, was es für Alternativen gibt.

Da bietet sich die Fallunterscheidung folgendermaßen an
```
ggT a b
 | b < 0 = ...
 | a < 0 = ...
 | ...
```
an, das ist m.M.n. übersichtlicher.

**Comment by Joemungandar** [comment]
Super, vielen Dank, ist beides verbessert :)
